# Generated by Django 3.1.7 on 2022-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220310_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
