# Generated by Django 3.1.7 on 2022-03-10 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220310_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_destination_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
