# Generated by Django 3.1.7 on 2022-03-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220312_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.FileField(upload_to='photos')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.destination')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.photo')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='photos',
            field=models.ManyToManyField(through='home.DestinationPhotos', to='home.Photo'),
        ),
    ]
