# Generated by Django 3.1.7 on 2022-04-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220401_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', through='home.DestinationLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destinationlike',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.destination'),
        ),
        migrations.AlterField(
            model_name='destinationlike',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.destination'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
