# Generated by Django 3.1.7 on 2022-06-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220401_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.CharField(blank=True, default='https://www.agora-gallery.com/advice/wp-content/uploads/2015/10/image-placeholder.png', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='destinationlike',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_likes', to='home.destination'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_ratings', to='home.destination'),
        ),
    ]
