# Generated by Django 3.1.7 on 2022-07-05 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220614_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reported', to='home.comment')),
                ('report_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
