# Generated by Django 3.1.7 on 2022-07-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_reportcomment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationcomments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_comments', to='home.comment'),
        ),
    ]
