# Generated by Django 3.1.7 on 2022-07-07 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_user_email_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LIKE', 'LIKE'), ('HEART', 'HEART'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY')], max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reactions', to='home.destination')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='reactions',
            field=models.ManyToManyField(through='home.DestinationReaction', to='home.Reaction'),
        ),
    ]
