# Generated by Django 3.1.7 on 2022-07-09 14:42

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_destinationreaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='manual_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
    ]
